/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_game_onsteroids_GameActivity */

#ifndef _Included_android_game_onsteroids_GameActivity
#define _Included_android_game_onsteroids_GameActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef android_game_onsteroids_GameActivity_MODE_PRIVATE
#define android_game_onsteroids_GameActivity_MODE_PRIVATE 0L
#undef android_game_onsteroids_GameActivity_MODE_WORLD_READABLE
#define android_game_onsteroids_GameActivity_MODE_WORLD_READABLE 1L
#undef android_game_onsteroids_GameActivity_MODE_WORLD_WRITEABLE
#define android_game_onsteroids_GameActivity_MODE_WORLD_WRITEABLE 2L
#undef android_game_onsteroids_GameActivity_MODE_APPEND
#define android_game_onsteroids_GameActivity_MODE_APPEND 32768L
#undef android_game_onsteroids_GameActivity_MODE_MULTI_PROCESS
#define android_game_onsteroids_GameActivity_MODE_MULTI_PROCESS 4L
#undef android_game_onsteroids_GameActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define android_game_onsteroids_GameActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef android_game_onsteroids_GameActivity_BIND_AUTO_CREATE
#define android_game_onsteroids_GameActivity_BIND_AUTO_CREATE 1L
#undef android_game_onsteroids_GameActivity_BIND_DEBUG_UNBIND
#define android_game_onsteroids_GameActivity_BIND_DEBUG_UNBIND 2L
#undef android_game_onsteroids_GameActivity_BIND_NOT_FOREGROUND
#define android_game_onsteroids_GameActivity_BIND_NOT_FOREGROUND 4L
#undef android_game_onsteroids_GameActivity_BIND_ABOVE_CLIENT
#define android_game_onsteroids_GameActivity_BIND_ABOVE_CLIENT 8L
#undef android_game_onsteroids_GameActivity_BIND_ALLOW_OOM_MANAGEMENT
#define android_game_onsteroids_GameActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef android_game_onsteroids_GameActivity_BIND_WAIVE_PRIORITY
#define android_game_onsteroids_GameActivity_BIND_WAIVE_PRIORITY 32L
#undef android_game_onsteroids_GameActivity_BIND_IMPORTANT
#define android_game_onsteroids_GameActivity_BIND_IMPORTANT 64L
#undef android_game_onsteroids_GameActivity_BIND_ADJUST_WITH_ACTIVITY
#define android_game_onsteroids_GameActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef android_game_onsteroids_GameActivity_CONTEXT_INCLUDE_CODE
#define android_game_onsteroids_GameActivity_CONTEXT_INCLUDE_CODE 1L
#undef android_game_onsteroids_GameActivity_CONTEXT_IGNORE_SECURITY
#define android_game_onsteroids_GameActivity_CONTEXT_IGNORE_SECURITY 2L
#undef android_game_onsteroids_GameActivity_CONTEXT_RESTRICTED
#define android_game_onsteroids_GameActivity_CONTEXT_RESTRICTED 4L
#undef android_game_onsteroids_GameActivity_RESULT_CANCELED
#define android_game_onsteroids_GameActivity_RESULT_CANCELED 0L
#undef android_game_onsteroids_GameActivity_RESULT_OK
#define android_game_onsteroids_GameActivity_RESULT_OK -1L
#undef android_game_onsteroids_GameActivity_RESULT_FIRST_USER
#define android_game_onsteroids_GameActivity_RESULT_FIRST_USER 1L
#undef android_game_onsteroids_GameActivity_DEFAULT_KEYS_DISABLE
#define android_game_onsteroids_GameActivity_DEFAULT_KEYS_DISABLE 0L
#undef android_game_onsteroids_GameActivity_DEFAULT_KEYS_DIALER
#define android_game_onsteroids_GameActivity_DEFAULT_KEYS_DIALER 1L
#undef android_game_onsteroids_GameActivity_DEFAULT_KEYS_SHORTCUT
#define android_game_onsteroids_GameActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef android_game_onsteroids_GameActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define android_game_onsteroids_GameActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef android_game_onsteroids_GameActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define android_game_onsteroids_GameActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeInitialize
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_android_game_onsteroids_GameActivity_nativeInitialize
  (JNIEnv *, jobject, jclass, jclass);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_game_onsteroids_GameActivity_nativeFinalize
  (JNIEnv *, jclass);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_game_onsteroids_GameActivity_nativeSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_android_game_onsteroids_GameActivity_nativeSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_game_onsteroids_GameActivity_nativeDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_game_onsteroids_GameActivity_nativePause
  (JNIEnv *, jclass);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_game_onsteroids_GameActivity_nativeResume
  (JNIEnv *, jclass);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeKeyDown
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_android_game_onsteroids_GameActivity_nativeKeyDown
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeKeyUp
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_android_game_onsteroids_GameActivity_nativeKeyUp
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     android_game_onsteroids_GameActivity
 * Method:    nativeTouchEvent
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_android_game_onsteroids_GameActivity_nativeTouchEvent
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
